[target.wasm32-unknown-unknown]
rustflags = [
    # Enabled unstable APIs from web_sys
    "--cfg=web_sys_unstable_apis",
]
runner = 'wasm-bindgen-test-runner'

[target.x86_64-pc-windows-gnu]
lto = true  
